spring:
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:postgresql://localhost:5432/umassgrades
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: "classpath:database-init.sql"
